### ISSUE TITLE
Add a section on References

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML-Proposal#23]
The explainer currently only mentions the HTML Design Principles. I think it's appropriate to also mention the [Web Platform Design Principles](https://w3ctag.github.io/design-principles/).

**Comment by prushforth** [comment]
Interesting, and agree these are an informative reference.   Will read, and add references as appropriate / that I recognize as applying in particular.  @shepazu recommended that I write two separate 'explainers', one which is a high-level one/two page executive summary-type explainer, and this one which goes deeper and in principle tries to follow the TAG advice on explainers, resulting in a lot of detail, which has resulted in people complaining that the explainer is too long.

Keeping this issue open as a way of saying to self: "Add a section on References", per the TAG guidelines template.

**Comment by prushforth** [comment]
> The explainer currently only mentions the HTML Design Principles. I think it's appropriate to also mention the [Web Platform Design Principles](https://w3ctag.github.io/design-principles/).

Found a good reference by browsing this document, the [TAG Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/#principles).  The latter could even factor into the requirements and use cases, I dare say.

**Comment by Malvoz** [comment]
Adding a list of references will make the documents longer, and the TAG explainer template does not include a list of references (neither do most W3C/WICG explainers). So maybe we should skip that?

**Comment by Malvoz** [comment]
OTOH I think it's vital to the [process](https://github.com/Maps4HTML/MapML-Proposal/issues/18) that principles/guidelines/requirements in documents such as the ones mentioned here (and in https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/163) are taken into consideration early on. That doesn't necessarily mean they have to be referenced in this proposal though.

**Comment by Malvoz** [comment]
> Found a good reference by browsing this document, the TAG Ethical Web Principles

The TAG Ethical Web Principles are linked from the Web Platform Design Principles.

And when you submit an [Early design review](https://github.com/w3ctag/design-reviews/issues/new/choose) to TAG there's an item to check if you've reviewed the Web Platform Design Principles, nothing about HTML design principles, I believe the former is simply treated as a successor to the latter.

We should close this issue out by replacing HTML design principles with Web Platform Design Principles. Don't think there's anything else to be done here.
